version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "MySql123456"
      MYSQL_DATABASE: "apisharp-db"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always

  api:
    build: .
    ports:
      - "8080:5000"
    restart: always
    depends_on:
      - db
