version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "MySql123456"
      MYSQL_DATABASE: "apisharp-db"
    volumes:
      - ./Data:/var/lib/mysql
    restart: always

  api:
    build: .
    container_name: api
    ports:
      - "8080:5000"
    volumes:
      - ./Logs:/app/Logs
    restart: always
